### ISSUE TITLE
How to train with mnist dataset

### ISSUE THREAD

**Issue by Johnson-yue** [ZhilZheng/Lr-LiVAE#3]
Hi , the faceScrub dataset is too large , so I want to train a small dataset first 

How to train with mnist , what configuration should be modified ??Would you give a demo ?

**Comment by johnnyasd12** [comment]
This modification for the code might help. 
https://github.com/johnnyasd12/Lr-LiVAE/commit/a48a3b8f1ce33e84a616eb215eea17f2d8c371e5

**Comment by Johnson-yue** [comment]
@johnnyasd12 you are so nice， I will try it， 3Q
